
[[paper]]
abstract = ''
author = ''
file = ''
keywords = ''
mendeley-tags = ''
title = ''
year = ''
annote = ''
journal = ''
pages = ''

[[paper]]
abstract = 'Buildings with intermittent occupancy may not perform thermally the same as typical commercial and residential facilities. Thermal comfort requirements require careful envelope design coupled with the appropriate air-conditioning system operation strategies. One of the most prominent examples of such buildings is mosques. Mosques are usually occupied five intermittent times day and night all year round. Like any other building, they have to be mechanically air-conditioned to achieve the required thermal comfort for worshippers especially in harsh climatic regions. This paper describes the physical and operating characteristics typical for the intermittently occupied mosques as well as the results of the thermal optimization of a medium size mosque in the two hot-dry and hot-humid Saudi Arabian cities of Riyadh and Jeddah. The analysis utilizes a direct search optimization technique that is coupled to an hourly energy simulation program. Based on that, design guidelines are presented for the optimum thermal performance of mosques in these two cities in addition to other design and operating factors that need to be considered for mosques in general. \textcopyright 2009 The Author(s).'
author = '西村勇亮'
file = ':Users/harukaneko/Google ドライブ/0_研究/0_menedley/mendeley_FileOrganizer/西村勇亮 - 2022 - 行動およびウェアラブルデータに基づくオフィスワーカーの心理指標の予測.pdf:pdf'
keywords = 'Thesis'
mendeley-tags = 'Thesis'
title = '行動およびウェアラブルデータに基づくオフィスワーカーの心理指標の予測'
year = '2022.0'
annote = ''
journal = ''
pages = ''

[[paper]]
abstract = ''
author = '田木真和 and 玉木悠 and 森川富昭 and 松久宗英 and 森口博基'
file = ':Users/harukaneko/Google ドライブ/0_研究/0_menedley/mendeley_FileOrganizer/田木真和 et al. - 2014 - NFC 通信歩数計を活用した健康データの 可視化による生活習慣の行動変容.pdf:pdf'
keywords = ''
mendeley-tags = ''
title = 'NFC 通信歩数計を活用した健康データの 可視化による生活習慣の行動変容'
year = '2014.0'
annote = '## In a word### Paper Link### Authores / University### Published date (yyyy/MM/dd)## Background## Contribution## Method## Result## Comment'
journal = '医療情報学'
pages = '281--291'
